import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "@global/context/provider.context";
import Logo from "@components/Logo";
import NavLeft from "@components/NavLeft";
import NavRight from "@components/NavRight";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provider>
          <div className="flex-center flex-col mt-6">
            <Logo />
          </div>
          <div className="grow w-mobil-layout m-auto ">{children}</div>
        </Provider>
        <NavLeft />
        <NavRight />
      </body>
    </html>
  );
}
